const wordList = [
  { word: "apple", hint: "A fruit that is red or green." },
  { word: 'banana', hint: 'A yellow tropical fruit.' },
  { word: 'carrot', hint: 'An orange vegetable.' },
  { word: 'elephant', hint: 'A large, gray animal with a long trunk.' },
  { word: 'computer', hint: 'A device used for processing data.' },
  { word: 'guitar', hint: 'A musical instrument with strings.' },
  { word: 'sunflower', hint: 'A tall plant with large, yellow flowers.' },
  { word: 'mountain', hint: 'A large landform that rises steeply above its surroundings.' },
  { word: 'chocolate', hint: 'A sweet treat made from cocoa beans.' },
  { word: 'telephone', hint: 'A communication device used to make calls.' },
  { word: 'ocean', hint: 'A vast body of saltwater.' },
  { word: 'book', hint: 'A written or printed work that can be read.' },
  { word: 'penguin', hint: 'A flightless bird that lives in cold regions.' },
  { word: 'bicycle', hint: 'A two-wheeled vehicle powered by pedaling.' },
  { word: 'umbrella', hint: 'A portable device used to shield from rain or sun.' },
  { word: 'pizza', hint: 'A popular Italian dish with cheese and toppings on a round crust.' },
  { word: 'butterfly', hint: 'A colorful insect with delicate, often patterned wings.' },
  { word: 'fireworks', hint: 'Explosive displays of light and color, often seen on celebrations.' },
  { word: 'telescope', hint: 'An optical instrument used to observe distant objects in space.' },
  { word: 'jazz', hint: 'A genre of music characterized by improvisation and syncopation.' },
  { word: 'sunglasses', hint: 'Eyewear designed to protect the eyes from the sun.' },
  { word: 'volcano', hint: 'A mountain that can erupt with molten rock, ash, and gases.' },
  { word: 'rainbow', hint: 'A meteorological phenomenon with a spectrum of colors.' },
  { word: 'octopus', hint: 'A marine animal known for its eight arms and intelligence.' },
  { word: 'ballet', hint: 'A graceful and expressive form of dance.' },
  { word: 'beach', hint: 'A sandy shore by the sea where people swim and sunbathe.' },
  { word: 'camera', hint: 'A device for capturing photographs or videos.' },
  { word: 'moonlight', hint: 'The soft, silvery light from the moon.' },
  { word: 'treasure', hint: 'Valuable items hidden or buried for discovery.' },
  { word: 'butterfly', hint: 'A colorful insect that undergoes metamorphosis.' },
  { word: 'adventure', hint: 'An exciting and unusual experience or journey.' },
  { word: 'chocolate', hint: 'A sweet treat made from cacao beans.' },
  { word: 'astronaut', hint: 'A person trained for traveling in space.' },
  { word: 'waterfall', hint: 'A natural cascade of water falling from a height.' },
  { word: 'unicorn', hint: 'A mythical horse-like creature with a single horn on its forehead.' },
]